version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: flood_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:16-alpine
    container_name: flood_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: flood
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: flood_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: